### PR TITLE
Update to latest YamlDotNet

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
There is a critical security vulnerability in v4, moving to latest.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@fearthecowboy I suppose all the generators will need to update as well when they pull in this commit?

**Review by vladbarosan — APPROVED** [review]

**Comment by fearthecowboy** [comment]
When they pull forward, yeah.

Shouldn't be much trouble, since everyone builds their own copy now.

**Review by fearthecowboy — COMMENTED** [review]
I'm assuming that everything works for you with this slight change?

**Comment by vladbarosan** [comment]
@fearthecowboy are these builds running on VSTS ? i was looking there and nothing seems to be queued

**Comment by jhendrixMSFT** [comment]
@fearthecowboy All `autorest.go` tests pass with this change.

**Review by fearthecowboy — APPROVED** [review]

**Comment by fearthecowboy** [comment]
Looks like I have to go update the build tasks.

**Pull request merged**
